### ISSUE TITLE
AttributeError: when executing show_sankey

### ISSUE THREAD

**Issue by krrome** [ricklupton/sankeyview#1]
I have tried to run the example you provide in the ipython notebook but I get a: AttributeError: 'DiGraph' object has no attribute 'get_node' error when I run the `sankey = show_sankey(sdd, dataset, width=800, height=500)` command in your example ipython notebook. Is that a known issue / am I using the wrong version of python or something like that?

Thank you!

I am using python 3.5.4 with the following environment:
attrs (17.3.0)
bleach (2.1.1)
certifi (2016.2.28)
decorator (4.1.2)
entrypoints (0.2.3)
html5lib (1.0b10)
ipykernel (4.6.1)
ipysankeywidget (0.2.2)
ipython (6.2.1)
ipython-genutils (0.2.0)
ipywidgets (7.0.5)
jedi (0.11.0)
Jinja2 (2.10)
jsonschema (2.6.0)
jupyter-client (5.1.0)
jupyter-core (4.4.0)
MarkupSafe (1.0)
mistune (0.8.3)
nbconvert (5.3.1)
nbformat (4.4.0)
networkx (2.0)
notebook (5.2.2)
numpy (1.13.3)
palettable (3.1.0)
pandas (0.21.0)
pandocfilters (1.4.2)
parso (0.1.0)
pexpect (4.3.0)
pickleshare (0.7.4)
pip (9.0.1)
prompt-toolkit (1.0.15)
ptyprocess (0.5.2)
Pygments (2.2.0)
python-dateutil (2.6.1)
pytz (2017.3)
pyzmq (16.0.3)
sankeyview (1.1.7)
setuptools (36.4.0)
simplegeneric (0.8.1)
six (1.11.0)
terminado (0.8.1)
testpath (0.3.1)
tornado (4.5.2)
traitlets (4.3.2)
wcwidth (0.1.7)
webencodings (0.5.1)
wheel (0.29.0)
widgetsnbextension (3.0.8)

**Comment by ricklupton** [comment]
Hi, thanks for your message. A new version 2.0 of networkx has [relatively] recently been released, with quite a different api. sankeyview needs the 1.x version.

Currently the install requirements of sankeyview don't specify versions which is bad -- we should update that.

In the meantime explicitly downgrading to networkx version 1.x (I have version 1.11) should get it working.

**Comment by krrome** [comment]
Thank you Rick, with networks version 1.11 show_sankey runs without error.
